export const SEED_DATA = {
  farmers: [
    {
      id: "farmer-1",
      name: "Ramesh Patil",
      email: "ramesh.patil@krishi.in",
      phone: "+91 98231 45678",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: {
        village: "Niphad",
        district: "Nashik",
        state: "Maharashtra",
        region: "Western Ghats Agro-Zone",
        pincode: "422303",
        coordinates: { lat: 20.0763, lng: 74.1086 }
      },
      farm: {
        id: "farm-1",
        name: "Patil Organic & Grain Farm",
        sizeAcres: 8.5,
        soilType: "Black Cotton Soil (Vertisol)",
        soilPH: 7.2,
        soilMoisture: 42, // percentage
        nitrogen: "Medium (240 kg/ha)",
        phosphorus: "High (35 kg/ha)",
        potassium: "High (290 kg/ha)",
        organicCarbon: "0.68%",
        irrigationSource: "Drip Irrigation & Borewell",
        primaryCrop: "Soybean",
        secondaryCrop: "Wheat",
        cropSeason: "Kharif-Rabi Transition",
        cropStage: "Pod Filling & Maturation",
        sowingDate: "2026-06-22",
        expectedHarvestDate: "2026-10-15"
      },
      category: "Small & Marginal",
      kisanCardNumber: "KCC-MH-2024-8891"
    },
    {
      id: "farmer-2",
      name: "Suresh Gowda",
      email: "suresh.gowda@krishi.in",
      phone: "+91 94480 12345",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: {
        village: "Mandya Rural",
        district: "Mandya",
        state: "Karnataka",
        region: "Southern Dry Zone",
        pincode: "571401",
        coordinates: { lat: 12.5218, lng: 76.8951 }
      },
      farm: {
        id: "farm-2",
        name: "Kaveri Green Acres",
        sizeAcres: 12.0,
        soilType: "Red Sandy Loam",
        soilPH: 6.8,
        soilMoisture: 55,
        irrigationSource: "Canal & Sprinkler",
        primaryCrop: "Sugarcane",
        secondaryCrop: "Rice",
        cropSeason: "Annual",
        cropStage: "Grand Growth Stage",
        sowingDate: "2026-02-10",
        expectedHarvestDate: "2026-12-20"
      },
      category: "Medium Landholder",
      kisanCardNumber: "KCC-KA-2023-4512"
    },
    {
      id: "farmer-3",
      name: "Arvind Patel",
      email: "arvind.patel@krishi.in",
      phone: "+91 98250 99881",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: {
        village: "Gondal",
        district: "Rajkot",
        state: "Gujarat",
        region: "Saurashtra Zone",
        pincode: "360311",
        coordinates: { lat: 21.9619, lng: 70.7984 }
      },
      farm: {
        id: "farm-3",
        name: "Sardar Gold Cotton Farms",
        sizeAcres: 15.0,
        soilType: "Medium Black Soil",
        soilPH: 7.6,
        soilMoisture: 38,
        irrigationSource: "Drip Irrigation",
        primaryCrop: "Cotton",
        secondaryCrop: "Groundnut",
        cropSeason: "Kharif",
        cropStage: "Boll Formation Stage",
        sowingDate: "2026-06-15",
        expectedHarvestDate: "2026-11-20"
      },
      category: "Medium Landholder",
      kisanCardNumber: "KCC-GJ-2024-7721"
    },
    {
      id: "farmer-4",
      name: "Rajesh Sharma",
      email: "rajesh.sharma@krishi.in",
      phone: "+91 97555 43210",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: {
        village: "Sanwer",
        district: "Indore",
        state: "Madhya Pradesh",
        region: "Malwa Plateau",
        pincode: "453551",
        coordinates: { lat: 22.9774, lng: 75.8273 }
      },
      farm: {
        id: "farm-4",
        name: "Malwa Agro Fields",
        sizeAcres: 6.0,
        soilType: "Deep Black Soil",
        soilPH: 7.4,
        soilMoisture: 46,
        irrigationSource: "Tube Well",
        primaryCrop: "Wheat",
        secondaryCrop: "Soybean",
        cropSeason: "Rabi Prep",
        cropStage: "Pre-Sowing Land Prep",
        sowingDate: "2026-10-25",
        expectedHarvestDate: "2027-03-30"
      },
      category: "Small & Marginal",
      kisanCardNumber: "KCC-MP-2023-3390"
    },
    {
      id: "farmer-5",
      name: "Dilip Verma",
      email: "dilip.verma@krishi.in",
      phone: "+91 94150 88231",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: {
        village: "Khair",
        district: "Aligarh",
        state: "Uttar Pradesh",
        region: "Western Indo-Gangetic Plains",
        pincode: "202138",
        coordinates: { lat: 27.9472, lng: 77.8427 }
      },
      farm: {
        id: "farm-5",
        name: "Ganga Valley Agri Farms",
        sizeAcres: 10.0,
        soilType: "Alluvial Sandy Loam",
        soilPH: 7.1,
        soilMoisture: 50,
        irrigationSource: "Tubewell & Canal",
        primaryCrop: "Potato",
        secondaryCrop: "Maize",
        cropSeason: "Rabi",
        cropStage: "Vegetative Growth",
        sowingDate: "2026-10-05",
        expectedHarvestDate: "2027-01-20"
      },
      category: "Medium Landholder",
      kisanCardNumber: "KCC-UP-2024-1102"
    }
  ],

  labourers: [
    {
      id: "labour-1",
      name: "Pandurang Shinde",
      email: "pandurang.shinde@krishi.in",
      phone: "+91 98601 22345",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Niphad, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Niphad, Dindori, Yeola",
      skills: ["Harvesting", "Crop Maintenance", "Fruit Picking", "Weeding"],
      experienceYears: 8,
      availability: "Immediate",
      expectedDailyWage: 450,
      rating: 4.9,
      completedJobsCount: 47,
      isVerified: true,
      bio: "Skilled in grape pruning, soybean harvesting, and onion picking with 8 years of farm experience."
    },
    {
      id: "labour-2",
      name: "Vikas Rathore",
      email: "vikas.rathore@krishi.in",
      phone: "+91 97130 55432",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Sanwer, Indore, Madhya Pradesh",
      district: "Indore",
      state: "Madhya Pradesh",
      preferredWorkArea: "Indore, Sanwer, Ujjain, Dewas",
      skills: ["Machinery Operator", "Ploughing", "Fertilizer Application", "Harvesting"],
      experienceYears: 10,
      availability: "Immediate",
      expectedDailyWage: 650,
      rating: 4.8,
      completedJobsCount: 62,
      isVerified: true,
      bio: "Expert Tractor and Harvester operator with heavy equipment license and mechanical maintenance experience."
    },
    {
      id: "labour-3",
      name: "Sunita Devi",
      email: "sunita.devi@krishi.in",
      phone: "+91 94520 77123",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Khair, Aligarh, Uttar Pradesh",
      district: "Aligarh",
      state: "Uttar Pradesh",
      preferredWorkArea: "Aligarh, Khair, Mathura, Hathras",
      skills: ["Sowing", "Weeding", "Vegetable Harvesting", "General Farm Labour"],
      experienceYears: 6,
      availability: "Immediate",
      expectedDailyWage: 380,
      rating: 4.7,
      completedJobsCount: 35,
      isVerified: true,
      bio: "Leads a 6-person women agricultural labour team for transplanting and weed management."
    },
    {
      id: "labour-4",
      name: "Manjunath K.",
      email: "manjunath.k@krishi.in",
      phone: "+91 94812 66341",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Mandya Rural, Mandya, Karnataka",
      district: "Mandya",
      state: "Karnataka",
      preferredWorkArea: "Mandya, Mysuru, Maddur, Ramanagara",
      skills: ["Irrigation", "Pesticide Application", "Crop Maintenance", "Harvesting"],
      experienceYears: 7,
      availability: "This Week",
      expectedDailyWage: 500,
      rating: 4.9,
      completedJobsCount: 51,
      isVerified: true,
      bio: "Specialized in sugarcane cutting and drip line maintenance with certified safety practices."
    },
    {
      id: "labour-5",
      name: "Bharat Solanki",
      email: "bharat.solanki@krishi.in",
      phone: "+91 98795 33219",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Gondal, Rajkot, Gujarat",
      district: "Rajkot",
      state: "Gujarat",
      preferredWorkArea: "Rajkot, Gondal, Jetpur, Junagadh",
      skills: ["Machinery Operator", "Ploughing", "Sowing", "Fertilizer Application"],
      experienceYears: 9,
      availability: "Immediate",
      expectedDailyWage: 600,
      rating: 4.8,
      completedJobsCount: 58,
      isVerified: true,
      bio: "Tractor driver experienced with rotavators, seed drills, and precision groundnut diggers."
    },
    {
      id: "labour-6",
      name: "Anand Gaikwad",
      email: "anand.gaikwad@krishi.in",
      phone: "+91 98229 11094",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Dindori, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Dindori, Niphad, Igatpuri",
      skills: ["Harvesting", "Fruit Picking", "Weeding", "Crop Maintenance"],
      experienceYears: 5,
      availability: "Immediate",
      expectedDailyWage: 420,
      rating: 4.7,
      completedJobsCount: 29,
      isVerified: true,
      bio: "Fast and diligent worker in tomato picking, onion grading, and soybean harvest."
    },
    {
      id: "labour-7",
      name: "Sachin More",
      email: "sachin.more@krishi.in",
      phone: "+91 99700 88712",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Yeola, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Yeola, Niphad, Kopargaon",
      skills: ["Pesticide Application", "Machinery Operator", "Fertilizer Application", "Irrigation"],
      experienceYears: 6,
      availability: "Next Week",
      expectedDailyWage: 520,
      rating: 4.6,
      completedJobsCount: 38,
      isVerified: true,
      bio: "Trained in backpack power sprayers, micro-irrigation valve tuning, and chemical safety."
    },
    {
      id: "labour-8",
      name: "Pooja Jadhav",
      email: "pooja.jadhav@krishi.in",
      phone: "+91 98221 44556",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Lasalgaon, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Lasalgaon, Chandwad, Niphad",
      skills: ["Vegetable Harvesting", "Sowing", "Weeding", "General Farm Labour"],
      experienceYears: 7,
      availability: "Immediate",
      expectedDailyWage: 400,
      rating: 4.9,
      completedJobsCount: 54,
      isVerified: true,
      bio: "Expert in delicate onion harvest, nursery seedling transplantation, and grading."
    },
    {
      id: "labour-9",
      name: "Kiran Waghmare",
      email: "kiran.waghmare@krishi.in",
      phone: "+91 97654 33210",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Panchavati, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Niphad, Sinnar, Trimbak",
      skills: ["Drone Operator", "Pesticide Application", "Machinery Operator"],
      experienceYears: 4,
      availability: "Immediate",
      expectedDailyWage: 850,
      rating: 5.0,
      completedJobsCount: 42,
      isVerified: true,
      bio: "DGCA-certified agricultural drone pilot for precision nano-urea and bio-pesticide spraying."
    },
    {
      id: "labour-10",
      name: "Tukaram Shinde",
      email: "tukaram.shinde@krishi.in",
      phone: "+91 98600 55678",
      passwordHash: "$2a$10$wT0o3q6E8uL9vYhXnZ2KReiJm.kI/1vOuE4vPzN2fS5G4E9tK0.7u",
      location: "Sinnar, Nashik, Maharashtra",
      district: "Nashik",
      state: "Maharashtra",
      preferredWorkArea: "Nashik, Sinnar, Sangamner, Niphad",
      skills: ["Ploughing", "Harvesting", "General Farm Labour", "Crop Maintenance"],
      experienceYears: 12,
      availability: "Immediate",
      expectedDailyWage: 450,
      rating: 4.8,
      completedJobsCount: 88,
      isVerified: true,
      bio: "Veteran agricultural hand with deep knowledge of seasonal Kharif and Rabi farm tasks."
    }
  ],

  machinery: [
    {
      id: "mach-1",
      name: "Mahindra 575 DI (45 HP Tractor)",
      category: "Tractor",
      provider: "Nashik Kisan Seva Kendra & Custom Hiring Centre",
      contact: "+91 98230 11223",
      location: "Niphad, Nashik, Maharashtra",
      distanceKm: 4.2,
      availability: "Available Today",
      rentalPricePerHour: 650,
      rentalPricePerAcre: 900,
      capacity: "45 Horse Power / 4-Cylinder",
      suitableCrops: ["Soybean", "Wheat", "Cotton", "Maize", "Sugarcane", "Onion"],
      features: ["Heavy Duty Hydraulics", "Dual Clutch", "Rotavator Compatible"],
      rating: 4.9,
      imageUrl: "https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-2",
      name: "Preet 987 Self-Propelled Combine Harvester",
      category: "Harvester",
      provider: "Godavari Agri Mechanization Hub",
      contact: "+91 98233 44556",
      location: "Lasalgaon, Nashik, Maharashtra",
      distanceKm: 8.5,
      availability: "Available from Tomorrow",
      rentalPricePerHour: 1800,
      rentalPricePerAcre: 1600,
      capacity: "101 HP / 4.2m Cutter Bar",
      suitableCrops: ["Wheat", "Soybean", "Paddy (Rice)", "Maize", "Mustard"],
      features: ["Grain Tank 2.4 m³", "Straw Chopper", "Grain Loss < 1.2%"],
      rating: 4.9,
      imageUrl: "https://images.unsplash.com/photo-1589923188900-85dae523342b?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-3",
      name: "Shaktiman Regular Light 6ft Rotavator",
      category: "Rotavator",
      provider: "Panchavati Custom Hiring Centre",
      contact: "+91 97654 88990",
      location: "Dindori, Nashik, Maharashtra",
      distanceKm: 6.1,
      availability: "Available Today",
      rentalPricePerHour: 450,
      rentalPricePerAcre: 700,
      capacity: "42 Multi-Speed L-Blades",
      suitableCrops: ["All Crops", "Soybean", "Wheat", "Vegetables", "Onion"],
      features: ["Fine Seedbed Preparation", "Residue Mixing", "High Fuel Efficiency"],
      rating: 4.8,
      imageUrl: "https://images.unsplash.com/photo-1594771804886-a933bb2d609b?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-4",
      name: "Garuda Kisan Agri Drone Sprayer (16L)",
      category: "Drone",
      provider: "Kisan Smart Tech FPO",
      contact: "+91 98222 77889",
      location: "Nashik Urban, Maharashtra",
      distanceKm: 11.0,
      availability: "Available on Booking",
      rentalPricePerHour: 950,
      rentalPricePerAcre: 450,
      capacity: "16 Litre Tank / 1 Acre in 7 mins",
      suitableCrops: ["Cotton", "Soybean", "Wheat", "Onion", "Tomato", "Sugarcane"],
      features: ["Centrifugal Atomizing Nozzles", "Obstacle Avoidance Radar", "DGCA Certified Pilot Included"],
      rating: 5.0,
      imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-5",
      name: "Fieldking Multi-Crop Pneumatic Planter & Seeder",
      category: "Seeder",
      provider: "Niphad Taluka Sahakari Sangh",
      contact: "+91 94222 33110",
      location: "Niphad, Nashik, Maharashtra",
      distanceKm: 3.8,
      availability: "Available Today",
      rentalPricePerHour: 400,
      rentalPricePerAcre: 600,
      capacity: "9-Row Precision Seed & Fertilizer Drill",
      suitableCrops: ["Soybean", "Wheat", "Maize", "Chickpea"],
      features: ["Zero Tillage Capability", "Precise Seed Spacing", "Simultaneous Fertilizer Drop"],
      rating: 4.7,
      imageUrl: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-6",
      name: "Aspee 500L Tractor Mounted Boom Sprayer",
      category: "Sprayer",
      provider: "Sahyadri Farmers Producer Co.",
      contact: "+91 98231 66778",
      location: "Dindori Road, Nashik, Maharashtra",
      distanceKm: 7.2,
      availability: "Available Today",
      rentalPricePerHour: 400,
      rentalPricePerAcre: 350,
      capacity: "500 Litre / 12-meter Spray Width",
      suitableCrops: ["Soybean", "Wheat", "Cotton", "Vegetables", "Onion"],
      features: ["Anti-Drip Nozzles", "Uniform Droplet Penetration", "High Pressure Triplex Pump"],
      rating: 4.7,
      imageUrl: "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-7",
      name: "Landforce Laser Land Leveler with Transmitter",
      category: "Cultivator",
      provider: "Maha Agri Machinery Hub",
      contact: "+91 94230 44551",
      location: "Pimpalgaon, Nashik, Maharashtra",
      distanceKm: 9.0,
      availability: "Available from Tomorrow",
      rentalPricePerHour: 800,
      rentalPricePerAcre: 1100,
      capacity: "7ft Blade / 2mm Grade Accuracy",
      suitableCrops: ["Wheat", "Rice", "Sugarcane", "Soybean"],
      features: ["Saves 25-30% Irrigation Water", "Increases Yield by 15%", "Laser Grade Controlled"],
      rating: 4.9,
      imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: "mach-8",
      name: "Kirloskar 7.5 HP High-Discharge Solar Pump Set",
      category: "Irrigation Pump",
      provider: "Kisan Urja Mitra",
      contact: "+91 98220 99001",
      location: "Yeola, Nashik, Maharashtra",
      distanceKm: 14.0,
      availability: "Available on Booking",
      rentalPricePerHour: 200,
      rentalPricePerAcre: 300,
      capacity: "7.5 HP / 55,000 Litres/hour",
      suitableCrops: ["All Crops", "Sugarcane", "Wheat", "Onion", "Vegetables"],
      features: ["Zero Fuel Cost", "Solar Tracking System", "Mobile Starter Remote"],
      rating: 4.8,
      imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80"
    }
  ],

  schemes: [
    {
      id: "scheme-1",
      name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
      department: "Ministry of Agriculture & Farmers Welfare, Govt of India",
      description: "Direct income support of ₹6,000 per year in three equal instalments of ₹2,000 to all landholding farmer families across the country.",
      eligibility: "All landholding farmer families with cultivable land in their names. Subject to standard institutional exclusions.",
      benefits: "₹6,000/year direct bank transfer via Aadhaar-linked DBT account.",
      requiredDocuments: ["Aadhaar Card", "Land Holding Ownership Record (7/12 & 8A / Khatoni)", "Active Bank Account Passbook", "Mobile Number linked with Aadhaar"],
      applicationDeadline: "Open Year-Round (Continuous Enrollment)",
      status: "Active & Accepting Applications",
      category: "Income Support & DBT",
      suitableLandSize: ["Small & Marginal", "Medium Landholder", "Large Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://pmkisan.gov.in/",
      badge: "Flagship Direct Benefit"
    },
    {
      id: "scheme-2",
      name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
      department: "Department of Agriculture and Cooperation, Govt of India",
      description: "Comprehensive crop insurance scheme providing financial support to farmers suffering crop loss/damage arising out of unforeseen weather events, pests, and natural calamities.",
      eligibility: "Farmers growing notified crops in notified areas including sharecroppers and tenant farmers.",
      benefits: "Lowest actuarial premium: 2% for Kharif crops, 1.5% for Rabi crops, and 5% for annual commercial/horticultural crops. Remaining premium subsidized by Govt.",
      requiredDocuments: ["Land Record Proof (7/12)", "Sowing Certificate / Declaration", "Aadhaar Card", "Bank Passbook with IFSC"],
      applicationDeadline: "Kharif: July 31 | Rabi: December 31",
      status: "Active & Recommended",
      category: "Crop Insurance & Risk Mitigation",
      suitableLandSize: ["Small & Marginal", "Medium Landholder", "Large Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://pmfby.gov.in/",
      badge: "High Recommended for Current Stage"
    },
    {
      id: "scheme-3",
      name: "Sub-Mission on Agricultural Mechanization (SMAM)",
      department: "Mechanization & Technology Division, MoA&FW",
      description: "Financial subsidy from 40% to 50% for purchasing agricultural machinery (Tractors, Harvesters, Rotavators, Drone Sprayers) and setting up Custom Hiring Centres (CHC).",
      eligibility: "Small, marginal, SC/ST, and women farmers get priority with up to 50% subsidy; others receive 40% subsidy.",
      benefits: "Subsidy up to ₹1.25 Lakh on tractors, up to ₹4 Lakh on combine harvesters, and up to ₹5 Lakh (100% for FPOs) for Agri Drones.",
      requiredDocuments: ["Land Possession Certificate", "Aadhaar Card", "Caste Certificate (if applicable)", "Bank Account Details", "Quotation from authorized dealer"],
      applicationDeadline: "Ongoing for Current Financial Year",
      status: "Active - Subsidies Open",
      category: "Farm Mechanization Subsidy",
      suitableLandSize: ["Small & Marginal", "Medium Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://agrimachinery.nic.in/",
      badge: "Machinery Subsidy Available"
    },
    {
      id: "scheme-4",
      name: "Kisan Credit Card (KCC) Scheme",
      department: "National Bank for Agriculture and Rural Development (NABARD) & RBI",
      description: "Adequate and timely credit support from the banking system for agricultural and allied activities at an effective concessional interest rate of 4% per annum.",
      eligibility: "Individual/joint borrowers who are owner cultivators, tenant farmers, oral lessees, or sharecroppers.",
      benefits: "Credit limit up to ₹3 Lakh at just 4% interest with prompt repayment incentive (3% interest subvention). No collateral required up to ₹1.60 Lakh.",
      requiredDocuments: ["Duly filled application form", "Identity & Address Proof (Aadhaar, Voter ID)", "Land record certified by Revenue Authority", "Cropping pattern document"],
      applicationDeadline: "Open Round the Year",
      status: "Active",
      category: "Institutional Credit & Loan",
      suitableLandSize: ["Small & Marginal", "Medium Landholder", "Large Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://www.myscheme.gov.in/schemes/kcc",
      badge: "Low Interest Credit"
    },
    {
      id: "scheme-5",
      name: "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY - Per Drop More Crop)",
      department: "Department of Agriculture and Farmers Welfare",
      description: "Subsidies up to 55% for small/marginal farmers and 45% for other farmers to install Drip and Sprinkler Micro-Irrigation systems.",
      eligibility: "Farmers with cultivable land and an assured water source.",
      benefits: "Saves 40-50% irrigation water, increases crop yield by 20-30%, and reduces electricity/diesel costs. Direct capital subsidy deposited into bank account.",
      requiredDocuments: ["Land Document (7/12 & 8A)", "Water Source Certificate", "Electricity Connection / Pump details", "Aadhaar Card", "Soil & Water test report"],
      applicationDeadline: "Rolling Applications via State Portals",
      status: "Active",
      category: "Micro-Irrigation & Water Conservation",
      suitableLandSize: ["Small & Marginal", "Medium Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://pmksy.gov.in/",
      badge: "55% Drip Subsidy"
    },
    {
      id: "scheme-6",
      name: "Paramparagat Krishi Vikas Yojana (PKVY Organic Scheme)",
      department: "National Mission for Sustainable Agriculture (NMSA)",
      description: "Promotes organic farming through cluster approach with financial assistance of ₹50,000 per hectare for conversion, organic inputs, certification, and marketing.",
      eligibility: "Farmers willing to form clusters of 20 hectares or 50 farmers adopting certified organic practices.",
      benefits: "₹31,000/ha directly for organic inputs (bio-fertilizers, vermicompost), ₹8,800/ha for value addition and packaging.",
      requiredDocuments: ["Cluster Membership Form", "Aadhaar Card", "Land Record", "Bank Account Details"],
      applicationDeadline: "Season Start Enrollment",
      status: "Active",
      category: "Organic Farming & Soil Health",
      suitableLandSize: ["Small & Marginal", "Medium Landholder"],
      stateApplicability: "All India",
      officialUrl: "https://pgsindia-ncof.gov.in/pkvy/index.aspx",
      badge: "Organic Incentive"
    },
    {
      id: "scheme-7",
      name: "Agriculture Infrastructure Fund (AIF)",
      department: "Ministry of Agriculture and Farmers Welfare",
      description: "Medium-long term debt financing facility for investment in viable projects for post-harvest management infrastructure and community farming assets.",
      eligibility: "Farmers, FPOs, PACS, Agri-entrepreneurs, Startups, and Self Help Groups.",
      benefits: "3% interest subvention per annum up to a limit of ₹2 Crore for a maximum period of 7 years, along with CGTMSE credit guarantee coverage.",
      requiredDocuments: ["Project Report (DPR)", "Land Title / Lease Agreement", "Aadhaar & PAN", "Bank Statements", "FPO / Entity Registration"],
      applicationDeadline: "Active till 2032-33",
      status: "Active",
      category: "Storage & Post Harvest Infrastructure",
      suitableLandSize: ["Medium Landholder", "Large Landholder", "FPOs"],
      stateApplicability: "All India",
      officialUrl: "https://agriinfra.dac.gov.in/",
      badge: "Post-Harvest Infra"
    },
    {
      id: "scheme-8",
      name: "National Beekeeping & Honey Mission (NBHM)",
      department: "National Bee Board (NBB)",
      description: "Integrated development of scientific beekeeping to increase crop pollination productivity and supplement farm family income.",
      eligibility: "Small, marginal, and landless farmers, women SHGs, and beekeepers.",
      benefits: "Up to 80% subsidy on beehive boxes, honey extractors, and processing units.",
      requiredDocuments: ["Aadhaar Card", "Bank Details", "Training Certificate from KVK / NBB"],
      applicationDeadline: "Rolling Applications",
      status: "Active",
      category: "Allied Agriculture & Income Diversification",
      suitableLandSize: ["Small & Marginal"],
      stateApplicability: "All India",
      officialUrl: "https://nbm.nic.in/",
      badge: "Allied Farming"
    }
  ],

  marketPrices: [
    {
      crop: "Soybean",
      variety: "Yellow Soybean (JS-335 / JS-9560)",
      mandi: "Nashik APMC",
      district: "Nashik",
      state: "Maharashtra",
      minPrice: 4350,
      maxPrice: 4780,
      modalPrice: 4620,
      todayPrice: 4650,
      yesterdayPrice: 4580,
      priceChangePercent: 1.53,
      unit: "₹ / Quintal",
      arrivalsQuintal: 4200,
      tradeDate: "2026-08-29",
      marketGrade: "FAQ (Fair Average Quality)",
      trend: "Upward"
    },
    {
      crop: "Soybean",
      variety: "Yellow Soybean",
      mandi: "Indore Mandi (Choithram)",
      district: "Indore",
      state: "Madhya Pradesh",
      minPrice: 4500,
      maxPrice: 4950,
      modalPrice: 4820,
      todayPrice: 4850,
      yesterdayPrice: 4760,
      priceChangePercent: 1.89,
      unit: "₹ / Quintal",
      arrivalsQuintal: 8900,
      tradeDate: "2026-08-29",
      marketGrade: "Grade A",
      trend: "Upward"
    },
    {
      crop: "Soybean",
      variety: "Yellow Soybean",
      mandi: "Latur APMC",
      district: "Latur",
      state: "Maharashtra",
      minPrice: 4420,
      maxPrice: 4810,
      modalPrice: 4680,
      todayPrice: 4710,
      yesterdayPrice: 4690,
      priceChangePercent: 0.43,
      unit: "₹ / Quintal",
      arrivalsQuintal: 6100,
      tradeDate: "2026-08-29",
      marketGrade: "FAQ",
      trend: "Stable"
    },
    {
      crop: "Wheat",
      variety: "Sharbati / Lokwan",
      mandi: "Niphad APMC",
      district: "Nashik",
      state: "Maharashtra",
      minPrice: 2450,
      maxPrice: 2780,
      modalPrice: 2620,
      todayPrice: 2640,
      yesterdayPrice: 2630,
      priceChangePercent: 0.38,
      unit: "₹ / Quintal",
      arrivalsQuintal: 2800,
      tradeDate: "2026-08-29",
      marketGrade: "FAQ",
      trend: "Stable"
    },
    {
      crop: "Wheat",
      variety: "Sharbati Premium",
      mandi: "Sehore Mandi",
      district: "Sehore",
      state: "Madhya Pradesh",
      minPrice: 2950,
      maxPrice: 3450,
      modalPrice: 3250,
      todayPrice: 3280,
      yesterdayPrice: 3220,
      priceChangePercent: 1.86,
      unit: "₹ / Quintal",
      arrivalsQuintal: 5400,
      tradeDate: "2026-08-29",
      marketGrade: "Premium Sharbati",
      trend: "Upward"
    },
    {
      crop: "Wheat",
      variety: "Kalyan Sona",
      mandi: "Khanna Grain Market",
      district: "Ludhiana",
      state: "Punjab",
      minPrice: 2350,
      maxPrice: 2580,
      modalPrice: 2480,
      todayPrice: 2490,
      yesterdayPrice: 2495,
      priceChangePercent: -0.20,
      unit: "₹ / Quintal",
      arrivalsQuintal: 11200,
      tradeDate: "2026-08-29",
      marketGrade: "FAQ",
      trend: "Stable"
    },
    {
      crop: "Onion",
      variety: "Red Onion (Garva / Pol)",
      mandi: "Lasalgaon APMC (Asia's Largest)",
      district: "Nashik",
      state: "Maharashtra",
      minPrice: 2200,
      maxPrice: 2950,
      modalPrice: 2680,
      todayPrice: 2720,
      yesterdayPrice: 2550,
      priceChangePercent: 6.67,
      unit: "₹ / Quintal",
      arrivalsQuintal: 16500,
      tradeDate: "2026-08-29",
      marketGrade: "Export Quality & FAQ",
      trend: "Strong Upward"
    },
    {
      crop: "Onion",
      variety: "Red Onion",
      mandi: "Pune APMC (Gultekdi)",
      district: "Pune",
      state: "Maharashtra",
      minPrice: 2400,
      maxPrice: 3100,
      modalPrice: 2850,
      todayPrice: 2890,
      yesterdayPrice: 2740,
      priceChangePercent: 5.47,
      unit: "₹ / Quintal",
      arrivalsQuintal: 9800,
      tradeDate: "2026-08-29",
      marketGrade: "Medium / Big",
      trend: "Strong Upward"
    },
    {
      crop: "Onion",
      variety: "Red Onion",
      mandi: "Azadpur Mandi",
      district: "New Delhi",
      state: "Delhi",
      minPrice: 3100,
      maxPrice: 3800,
      modalPrice: 3500,
      todayPrice: 3550,
      yesterdayPrice: 3420,
      priceChangePercent: 3.80,
      unit: "₹ / Quintal",
      arrivalsQuintal: 14200,
      tradeDate: "2026-08-29",
      marketGrade: "Consumer Grade",
      trend: "Upward"
    },
    {
      crop: "Cotton",
      variety: "Medium Staple (Shankar-6)",
      mandi: "Rajkot APMC",
      district: "Rajkot",
      state: "Gujarat",
      minPrice: 6900,
      maxPrice: 7650,
      modalPrice: 7350,
      todayPrice: 7380,
      yesterdayPrice: 7290,
      priceChangePercent: 1.23,
      unit: "₹ / Quintal",
      arrivalsQuintal: 7200,
      tradeDate: "2026-08-29",
      marketGrade: "CCI Grade 1",
      trend: "Upward"
    },
    {
      crop: "Cotton",
      variety: "Long Staple (Bunny)",
      mandi: "Amravati APMC",
      district: "Amravati",
      state: "Maharashtra",
      minPrice: 6750,
      maxPrice: 7420,
      modalPrice: 7180,
      todayPrice: 7200,
      yesterdayPrice: 7150,
      priceChangePercent: 0.70,
      unit: "₹ / Quintal",
      arrivalsQuintal: 5100,
      tradeDate: "2026-08-29",
      marketGrade: "Grade A",
      trend: "Stable"
    },
    {
      crop: "Tomato",
      variety: "Hybrid Red",
      mandi: "Nashik APMC",
      district: "Nashik",
      state: "Maharashtra",
      minPrice: 1400,
      maxPrice: 2200,
      modalPrice: 1850,
      todayPrice: 1900,
      yesterdayPrice: 1750,
      priceChangePercent: 8.57,
      unit: "₹ / Quintal",
      arrivalsQuintal: 6800,
      tradeDate: "2026-08-29",
      marketGrade: "Fresh Red Table",
      trend: "Upward"
    },
    {
      crop: "Rice",
      variety: "Sona Masoori",
      mandi: "Raichur APMC",
      district: "Raichur",
      state: "Karnataka",
      minPrice: 3200,
      maxPrice: 3750,
      modalPrice: 3520,
      todayPrice: 3540,
      yesterdayPrice: 3530,
      priceChangePercent: 0.28,
      unit: "₹ / Quintal",
      arrivalsQuintal: 8400,
      tradeDate: "2026-08-29",
      marketGrade: "Paddy Raw",
      trend: "Stable"
    },
    {
      crop: "Maize",
      variety: "Yellow Feed Grade",
      mandi: "Davangere APMC",
      district: "Davangere",
      state: "Karnataka",
      minPrice: 2150,
      maxPrice: 2420,
      modalPrice: 2310,
      todayPrice: 2320,
      yesterdayPrice: 2290,
      priceChangePercent: 1.31,
      unit: "₹ / Quintal",
      arrivalsQuintal: 4300,
      tradeDate: "2026-08-29",
      marketGrade: "Standard",
      trend: "Upward"
    },
    {
      crop: "Sugarcane",
      variety: "Co-86032",
      mandi: "Mandya Sahakari Sakhar Karkhana",
      district: "Mandya",
      state: "Karnataka",
      minPrice: 3100,
      maxPrice: 3350,
      modalPrice: 3240,
      todayPrice: 3250,
      yesterdayPrice: 3250,
      priceChangePercent: 0.0,
      unit: "₹ / Tonne (FRP)",
      arrivalsQuintal: 25000,
      tradeDate: "2026-08-29",
      marketGrade: "High Sucrose",
      trend: "Fixed FRP"
    },
    {
      crop: "Potato",
      variety: "Kufri Jyoti / Pukhraj",
      mandi: "Agra APMC",
      district: "Agra",
      state: "Uttar Pradesh",
      minPrice: 1350,
      maxPrice: 1720,
      modalPrice: 1560,
      todayPrice: 1580,
      yesterdayPrice: 1540,
      priceChangePercent: 2.60,
      unit: "₹ / Quintal",
      arrivalsQuintal: 19500,
      tradeDate: "2026-08-29",
      marketGrade: "Medium Table",
      trend: "Upward"
    }
  ],

  historicalMarketRecords: [
    // 7-day, 30-day, seasonal records for chart graphing
    { date: "2026-08-23", soybean: 4420, wheat: 2600, onion: 2350, cotton: 7150, tomato: 1550 },
    { date: "2026-08-24", soybean: 4480, wheat: 2610, onion: 2420, cotton: 7200, tomato: 1620 },
    { date: "2026-08-25", soybean: 4510, wheat: 2615, onion: 2490, cotton: 7230, tomato: 1700 },
    { date: "2026-08-26", soybean: 4540, wheat: 2620, onion: 2540, cotton: 7260, tomato: 1680 },
    { date: "2026-08-27", soybean: 4560, wheat: 2625, onion: 2580, cotton: 7280, tomato: 1720 },
    { date: "2026-08-28", soybean: 4580, wheat: 2630, onion: 2650, cotton: 7320, tomato: 1780 },
    { date: "2026-08-29", soybean: 4650, wheat: 2640, onion: 2720, cotton: 7380, tomato: 1900 },
    // 30-day historical points
    { date: "2026-08-01", soybean: 4280, wheat: 2540, onion: 1980, cotton: 7000, tomato: 2300 },
    { date: "2026-08-07", soybean: 4320, wheat: 2560, onion: 2100, cotton: 7050, tomato: 2100 },
    { date: "2026-08-14", soybean: 4380, wheat: 2580, onion: 2250, cotton: 7110, tomato: 1850 },
    { date: "2026-08-21", soybean: 4430, wheat: 2595, onion: 2380, cotton: 7160, tomato: 1600 },
    // Monthly trend points for seasonal analysis
    { month: "Jan", soybean: 4950, wheat: 2400, onion: 1800, cotton: 7600, tomato: 1200 },
    { month: "Feb", soybean: 4850, wheat: 2380, onion: 1650, cotton: 7500, tomato: 1100 },
    { month: "Mar", soybean: 4700, wheat: 2320, onion: 1500, cotton: 7400, tomato: 1300 },
    { month: "Apr", soybean: 4650, wheat: 2350, onion: 1450, cotton: 7300, tomato: 1450 },
    { month: "May", soybean: 4600, wheat: 2420, onion: 1600, cotton: 7250, tomato: 1900 },
    { month: "Jun", soybean: 4500, wheat: 2480, onion: 1850, cotton: 7100, tomato: 2400 },
    { month: "Jul", soybean: 4350, wheat: 2520, onion: 2100, cotton: 7050, tomato: 2800 },
    { month: "Aug (Current)", soybean: 4650, wheat: 2640, onion: 2720, cotton: 7380, tomato: 1900 },
    { month: "Sep (Est)", soybean: 4820, wheat: 2680, onion: 3100, cotton: 7550, tomato: 1750 },
    { month: "Oct (Est)", soybean: 4980, wheat: 2720, onion: 3400, cotton: 7700, tomato: 1600 },
    { month: "Nov (Est)", soybean: 4750, wheat: 2760, onion: 2900, cotton: 7450, tomato: 1400 },
    { month: "Dec (Est)", soybean: 4850, wheat: 2800, onion: 2200, cotton: 7550, tomato: 1300 }
  ],

  labourRequirements: [
    {
      id: "req-1",
      farmerId: "farmer-1",
      farmerName: "Ramesh Patil",
      farmName: "Patil Organic & Grain Farm",
      crop: "Soybean",
      farmSizeAcres: 8.5,
      activity: "Harvesting & Threshing",
      workersRequired: 8,
      durationDays: 3,
      startDate: "2026-09-08",
      location: "Niphad, Nashik, Maharashtra",
      dailyWageOffered: 480,
      description: "Need 8 experienced workers for pod harvesting and threshing of JS-335 soybean on 8.5 acres. Lunch and morning tea provided.",
      requiredSkills: ["Harvesting", "Crop Maintenance"],
      status: "Open",
      applicantsCount: 4,
      createdAt: "2026-08-28T10:30:00Z"
    },
    {
      id: "req-2",
      farmerId: "farmer-1",
      farmerName: "Ramesh Patil",
      farmName: "Patil Organic & Grain Farm",
      crop: "Onion",
      farmSizeAcres: 3.0,
      activity: "Weeding & Earthing Up",
      workersRequired: 4,
      durationDays: 2,
      startDate: "2026-09-02",
      location: "Niphad, Nashik, Maharashtra",
      dailyWageOffered: 450,
      description: "Manual weeding in late kharif onion plots. Precision weed removal without disturbing root bulbs.",
      requiredSkills: ["Weeding", "Crop Maintenance"],
      status: "Open",
      applicantsCount: 2,
      createdAt: "2026-08-27T14:15:00Z"
    },
    {
      id: "req-3",
      farmerId: "farmer-2",
      farmerName: "Suresh Gowda",
      farmName: "Kaveri Green Acres",
      crop: "Sugarcane",
      farmSizeAcres: 12.0,
      activity: "Fertilizer Application & Earthing",
      workersRequired: 6,
      durationDays: 4,
      startDate: "2026-09-05",
      location: "Mandya Rural, Karnataka",
      dailyWageOffered: 520,
      description: "Applying basal dose and micro-nutrients in 5th month ratoon cane followed by ridge earthing.",
      requiredSkills: ["Fertilizer Application", "Crop Maintenance"],
      status: "Open",
      applicantsCount: 3,
      createdAt: "2026-08-28T09:00:00Z"
    }
  ],

  labourApplications: [
    {
      id: "app-1",
      requirementId: "req-1",
      labourId: "labour-1",
      labourName: "Pandurang Shinde",
      labourPhone: "+91 98601 22345",
      farmerId: "farmer-1",
      farmName: "Patil Organic & Grain Farm",
      activity: "Harvesting & Threshing",
      crop: "Soybean",
      wageExpected: 450,
      status: "Accepted",
      appliedDate: "2026-08-28T12:00:00Z",
      note: "Have 8 years experience in soybean harvesting. Can bring 2 additional workers if needed."
    },
    {
      id: "app-2",
      requirementId: "req-1",
      labourId: "labour-6",
      labourName: "Anand Gaikwad",
      labourPhone: "+91 98229 11094",
      farmerId: "farmer-1",
      farmName: "Patil Organic & Grain Farm",
      activity: "Harvesting & Threshing",
      crop: "Soybean",
      wageExpected: 420,
      status: "Pending",
      appliedDate: "2026-08-28T15:30:00Z",
      note: "Available for all 3 days. Ready to start early morning."
    },
    {
      id: "app-3",
      requirementId: "req-2",
      labourId: "labour-8",
      labourName: "Pooja Jadhav",
      labourPhone: "+91 98221 44556",
      farmerId: "farmer-1",
      farmName: "Patil Organic & Grain Farm",
      activity: "Weeding & Earthing Up",
      crop: "Onion",
      wageExpected: 400,
      status: "Accepted",
      appliedDate: "2026-08-27T16:00:00Z",
      note: "Expert in onion field weeding without damaging bulbs."
    }
  ],

  machineryBookings: [
    {
      id: "book-1",
      machineryId: "mach-2",
      machineryName: "Preet 987 Self-Propelled Combine Harvester",
      farmerId: "farmer-1",
      farmerName: "Ramesh Patil",
      farmLocation: "Niphad, Nashik",
      acreage: 8.5,
      bookingDate: "2026-09-10",
      totalCost: 13600,
      status: "Confirmed",
      paymentStatus: "Advance Paid (₹3,000)"
    }
  ],

  notifications: [
    {
      id: "notif-1",
      title: "Weather Alert: Heavy Showers Expected",
      message: "IMD predicts 35mm convective rainfall in Nashik district within next 36 hours. Postpone chemical foliar spraying.",
      category: "Weather",
      severity: "warning",
      timestamp: "2026-08-29T13:45:00Z",
      isRead: false
    },
    {
      id: "notif-2",
      title: "Market Price Spike: Onion Prices +6.67%",
      message: "Lasalgaon Mandi modal price reached ₹2,720/Qtl today. Up ₹170/Qtl from yesterday.",
      category: "Market",
      severity: "success",
      timestamp: "2026-08-29T12:00:00Z",
      isRead: false
    },
    {
      id: "notif-3",
      title: "Soil Moisture Alert: Pod Zone Moisture 42%",
      message: "Soil moisture in soybean root zone is optimal. With rain forecast tomorrow, skip scheduled furrow irrigation.",
      category: "Advisory",
      severity: "info",
      timestamp: "2026-08-29T10:15:00Z",
      isRead: false
    },
    {
      id: "notif-4",
      title: "New Labour Application Received",
      message: "Anand Gaikwad applied for your 'Harvesting & Threshing' labour requirement.",
      category: "Labour",
      severity: "info",
      timestamp: "2026-08-28T15:30:00Z",
      isRead: true
    },
    {
      id: "notif-5",
      title: "Government Scheme: SMAM Drone Subsidy",
      message: "SMAM Portal opens new window for 50% Agricultural Drone & Rotavator capital subsidy.",
      category: "Scheme",
      severity: "success",
      timestamp: "2026-08-27T09:00:00Z",
      isRead: true
    }
  ]
};
